[package]
name = "dprint-swc-ecma-ast-view"
version = "0.40.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
license = "MIT"
description = "View of the swc AST that's easier to navigate."

[features]
default = []
serialize = ["serde_json"]

[dependencies]
bumpalo = "3.7.1"
num-bigint = "0.2"
rustc-hash = "1.1.0"
serde_json = { version = "1.0.68", optional = true }
swc_atoms = "0.2.8"
swc_common = "0.13.5"
swc_ecmascript = { version = "0.77.0", features = ["parser"] }
text_lines = "0.3.0"

[dev-dependencies]
pretty_assertions = "0.7.2"
