[package]
name = "dprint-swc-ecma-ast-view"
version = "0.29.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
license = "MIT"
description = "View of the swc AST that's easier to navigate."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
serialize = ["serde_json"]

[dependencies]
bumpalo = "3.7.0"
fnv = "1.0.7"
num-bigint = "0.2"
serde_json = { version = "1.0.66", optional = true }
swc_atoms = "0.2.6"
swc_common = "0.11.4"
swc_ecmascript = { version = "0.52.1", features = ["parser"] }

[dev-dependencies]
pretty_assertions = "0.7.2"
