[package]
name = "dprint-swc-ecma-ast-view"
version = "0.1.0"
authors = ["David Sherret <dsherret@gmail.com>"]
description = "View of the swc AST that's easier to navigate."
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_common = "0.10.7"
swc_atoms = "0.2.5"
swc_ecmascript = { version = "0.15.0", features = ["parser"] }
num-bigint = "0.2"
bumpalo = "3.4.0"
