[package]
name = "dprint-swc-ecma-ast-view"
version = "0.1.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_ecma_ast = "0.35.0"
swc_common = "0.10.6"
swc_atoms = "0.2.5"
num-bigint = "0.2"

[dev-dependencies]
swc_ecma_parser = "0.43.1"