[package]
name = "dprint-swc-ext"
version = "0.3.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Functionality to make swc easier to work with."

[package.metadata.docs.rs]
all-features = true

[features]
sourcemap = ["swc_common/sourcemap"]
view = []

[dependencies]
bumpalo = "3.10.0"
num-bigint = "0.4"
rustc-hash = "1.1.0"
swc_atoms = "0.2.13"
swc_common = "0.23.0"
swc_ecma_ast = "0.84.0"
swc_ecma_parser = "0.111.0"
text_lines = "0.4.1"

[dev-dependencies]
pretty_assertions = "1.0.0"
