[package]
name = "dprint-swc-ecma-ast-view"
version = "0.52.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2021"
license = "MIT"
description = "View of the swc AST that's easier to navigate."

[dependencies]
bumpalo = "3.9.1"
num-bigint = "0.4"
rustc-hash = "1.1.0"
swc_atoms = "0.2.9"
swc_common = "0.17.17"
swc_ecmascript = { version = "0.133.0", features = ["parser"] }
text_lines = "0.4.1"

[dev-dependencies]
pretty_assertions = "1.0.0"
