[package]
name = "dprint-swc-ecma-ast-view"
version = "0.36.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
license = "MIT"
description = "View of the swc AST that's easier to navigate."

[features]
default = []
serialize = ["serde_json"]

[dependencies]
bumpalo = "3.7.0"
fnv = "1.0.7"
num-bigint = "0.2"
serde_json = { version = "1.0.66", optional = true }
swc_atoms = "0.2.7"
swc_common = "0.12.2"
swc_ecmascript = { version = "0.64.0", features = ["parser"] }
text_lines = "0.3.0"

[dev-dependencies]
pretty_assertions = "0.7.2"
